# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 735163059e5b61d3709231426b19d5a8eb000b1a1274fe7a8a3b173e3f9e37fc3024223e50e1fd209fabecf1d8d06ce30da48827ff282ea9a61b08e6dec5b061

test:
  secret_key_base: 2334de5c1160596c3799fc4f80b9e04e179c3966e5c67dec627f391c731caae4e69286933caec53a64c552402dac289edf893eb84a7ccf5c04996992c79bedaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
